export const STOCK_ADJUSTMENT_ACTION = {
  ADD: "ADD",
  REDUCE: "REDUCE",
};
export const STOCK_ADJUSTMENT_REASONS_FOR_ADDITION = [
  "PURCHASE",
  "CORRECTION",
  "OTHER",
];
export const STOCK_ADJUSTMENT_REASONS_FOR_REDUCTION = [
  "SALE",
  "DAMAGE",
  "CORRECTION",
  "OTHER",
];
